global:
    scrape_interval: 15s

    # Attach these labels to any time series or alerts when communicating with
    # external systems (federation, remote storage, Alertmanager).
    external_labels:
        monitor: 'kafka-monitor'

scrape_configs:
    - job_name: 'crypto-price-api'
      scrape_interval: 5s
      static_configs:
        - targets:
            - crypto-price-api:2112

    - job_name: 'crypto-price-change-tracker'
      scrape_interval: 5s
      static_configs:
        - targets:
            - crypto-price-change-tracker:2112

    - job_name: 'crypto-price-producer'
      scrape_interval: 5s
      static_configs:
        - targets:
            - btc-crypto-price-producer:2112
            - ltc-crypto-price-producer:2112
            - xrp-crypto-price-producer:2112
            - xmr-crypto-price-producer:2112
    # Scrape Kafka data
    - job_name: 'zookeeper'
      scrape_interval: 5s
      static_configs:
        - targets:
            - zookeeper-1:8091
    - job_name: 'kafka-broker'
      scrape_interval: 5s
      static_configs:
        - targets:
            - kafka-1:8091
