apiVersion: apps/v1
kind: Deployment
metadata:
  name: sexy-server-producer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sexy-server-producer
  template:
    metadata:
      labels:
        app: sexy-server-producer
    spec:
      containers:
      - name: sexy-server-producer
        image: sexy-server-producer
        imagePullPolicy: Never
        resources:
          requests:
            cpu: 200m
            memory: 100Mi
          limits:
            cpu: 500m
            memory: 512Mi
        env:
        - name: KAFKA_SERVER
          value: "192.168.49.1:9091"
        - name: KAFKA_PARTITION
          value: "0"
---
# Create service definition so pod can be referenced by DNS @ cpuhog.default.svc.cluster.
### Help: `kubectl apply -f dns-utils.yaml && kubectl exec -ti dnsutils -- nslookup cpuhog`
# Can be referenced within a terminal by `wget -q -O- http://echo-server.default.svc.cluster.local:8080`
apiVersion: v1
kind: Service
metadata:
  name: sexy-server-producer
spec:
  selector:
    app: sexy-server-producer
  type: LoadBalancer
  ports:
    - port: 8080 # External port
      targetPort: 8080 # Pod port
