- name: Create Secrets Manager
  hosts: localhost
  gather_facts: false
  vars:
    secrets_name: pik-auto-test-1
  tasks: 
    - assert:
        that:
        - aws_access_key != ""
        - aws_secret_key != ""
        - conf_api_url != ""
        - conf_db_host != ""
        - conf_db_port != ""
        - conf_db_user != ""
        - conf_db_pass != ""
    - name: Set AWS default varaibles
      set_fact:
        aws_region: ap-southeast-2
        tag_secret_manager_creation_time: "{{ '%Y%m%d-%H%M%S' | strftime }}"
    - name: Create Secret Manager 
      include_role:
        name: create_secrets_manager 
    